In [1]:
import os
import numpy as np
import pandas as pd
import sklearn.model_selection
import tensorflow as tf

import EvaluationDataAccess as DataAccess

In [2]:
print(os.getcwd())

C:\Users\Piotr\Documents\proj\chess\ml-poc


In [3]:
X, Y = DataAccess.get_all_evaluated_records()
X = np.array([DataAccess.fen_positon_to_one_hot_vector(fen) for fen in X])

X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, Y, test_size=0.33)

In [4]:
print(X_train)

[[ 1  0  0 ...  0  1  0]
 [-1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  1  0]
 ...
 [ 1  1  1 ...  0  0  0]
 [-1  0  0 ...  0  0  0]
 [ 1  0  0 ...  1  0  0]]


In [5]:
print(X.shape)

(37498, 773)


In [6]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(500, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1, activation="relu")])

model.compile(loss="mean_squared_logarithmic_error", optimizer="sgd", metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
786/786 [==============================] - 6s 6ms/step - loss: 12.4172 - mean_squared_logarithmic_error: 12.4172 - val_loss: 11.6988 - val_mean_squared_logarithmic_error: 11.6988
Epoch 2/150
786/786 [==============================] - 4s 5ms/step - loss: 11.6451 - mean_squared_logarithmic_error: 11.6451 - val_loss: 11.3001 - val_mean_squared_logarithmic_error: 11.3001
Epoch 3/150
786/786 [==============================] - 4s 6ms/step - loss: 11.0757 - mean_squared_logarithmic_error: 11.0757 - val_loss: 10.6478 - val_mean_squared_logarithmic_error: 10.6478
Epoch 4/150
786/786 [==============================] - 5s 6ms/step - loss: 10.4357 - mean_squared_logarithmic_error: 10.4357 - val_loss: 10.0996 - val_mean_squared_logarithmic_error: 10.0996
Epoch 5/150
786/786 [==============================] - 5s 6ms/step - loss: 9.9094 - mean_squared_logarithmic_error: 9.9094 - val_loss: 9.7425 - val_mean_squared_logarithmic_error: 9.7425
Epoch 6/150
786/786 [============================

In [7]:
model.save("chess500r100r1r.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess500r100r1r.tf\assets


INFO:tensorflow:Assets written to: chess500r100r1r.tf\assets


In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(500, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation="relu")])

model.compile(loss="mean_squared_logarithmic_error", optimizer="sgd", metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
786/786 [==============================] - 7s 8ms/step - loss: 12.4422 - mean_squared_logarithmic_error: 12.4422 - val_loss: 11.7108 - val_mean_squared_logarithmic_error: 11.7108
Epoch 2/150
786/786 [==============================] - 6s 7ms/step - loss: 11.6704 - mean_squared_logarithmic_error: 11.6704 - val_loss: 11.3276 - val_mean_squared_logarithmic_error: 11.3276
Epoch 3/150
786/786 [==============================] - 6s 7ms/step - loss: 11.1221 - mean_squared_logarithmic_error: 11.1221 - val_loss: 10.6918 - val_mean_squared_logarithmic_error: 10.6918
Epoch 4/150
786/786 [==============================] - 5s 7ms/step - loss: 10.4902 - mean_squared_logarithmic_error: 10.4902 - val_loss: 10.2403 - val_mean_squared_logarithmic_error: 10.2403
Epoch 5/150
786/786 [==============================] - 6s 7ms/step - loss: 9.9969 - mean_squared_logarithmic_error: 9.9969 - val_loss: 9.7558 - val_mean_squared_logarithmic_error: 9.7558
Epoch 6/150
786/786 [============================

In [9]:
model.save("chess500r100r1rDO.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess500r100r1rDO.tf\assets


INFO:tensorflow:Assets written to: chess500r100r1rDO.tf\assets


In [10]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(1, activation="relu")])
model.compile(loss="mean_squared_logarithmic_error", optimizer="sgd", metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
786/786 [==============================] - 7s 7ms/step - loss: 12.5013 - mean_squared_logarithmic_error: 12.5013 - val_loss: 11.6988 - val_mean_squared_logarithmic_error: 11.6988
Epoch 2/150
786/786 [==============================] - 5s 7ms/step - loss: 11.6607 - mean_squared_logarithmic_error: 11.6607 - val_loss: 11.3462 - val_mean_squared_logarithmic_error: 11.3462
Epoch 3/150
786/786 [==============================] - 5s 7ms/step - loss: 11.1297 - mean_squared_logarithmic_error: 11.1297 - val_loss: 10.7012 - val_mean_squared_logarithmic_error: 10.7012
Epoch 4/150
786/786 [==============================] - 5s 7ms/step - loss: 10.4796 - mean_squared_logarithmic_error: 10.4796 - val_loss: 10.1331 - val_mean_squared_logarithmic_error: 10.1331
Epoch 5/150
786/786 [==============================] - 6s 7ms/step - loss: 9.9663 - mean_squared_logarithmic_error: 9.9663 - val_loss: 9.7381 - val_mean_squared_logarithmic_error: 9.7381
Epoch 6/150
786/786 [============================

In [11]:
model.save("chess1000r200r1r.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess1000r200r1r.tf\assets


INFO:tensorflow:Assets written to: chess1000r200r1r.tf\assets


In [12]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation="relu")])
model.compile(loss="mean_squared_logarithmic_error", optimizer="sgd", metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
786/786 [==============================] - 7s 8ms/step - loss: 12.3944 - mean_squared_logarithmic_error: 12.3944 - val_loss: 11.7044 - val_mean_squared_logarithmic_error: 11.7044
Epoch 2/150
786/786 [==============================] - 6s 8ms/step - loss: 11.6723 - mean_squared_logarithmic_error: 11.6723 - val_loss: 11.3603 - val_mean_squared_logarithmic_error: 11.3603
Epoch 3/150
786/786 [==============================] - 7s 9ms/step - loss: 11.1752 - mean_squared_logarithmic_error: 11.1752 - val_loss: 10.7586 - val_mean_squared_logarithmic_error: 10.7586
Epoch 4/150
786/786 [==============================] - 7s 9ms/step - loss: 10.5543 - mean_squared_logarithmic_error: 10.5543 - val_loss: 10.2055 - val_mean_squared_logarithmic_error: 10.2055
Epoch 5/150
786/786 [==============================] - 7s 8ms/step - loss: 10.0315 - mean_squared_logarithmic_error: 10.0315 - val_loss: 9.7548 - val_mean_squared_logarithmic_error: 9.7548
Epoch 6/150
786/786 [==========================

In [13]:
model.save("chess1000r200r1rDO.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess1000r200r1rDO.tf\assets


INFO:tensorflow:Assets written to: chess1000r200r1rDO.tf\assets


In [14]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(1, activation="relu")])
model.compile(loss="mean_squared_logarithmic_error", optimizer="sgd", metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
786/786 [==============================] - 11s 13ms/step - loss: 12.0956 - mean_squared_logarithmic_error: 12.0956 - val_loss: 11.4412 - val_mean_squared_logarithmic_error: 11.4412
Epoch 2/150
786/786 [==============================] - 9s 12ms/step - loss: 10.9945 - mean_squared_logarithmic_error: 10.9945 - val_loss: 10.2744 - val_mean_squared_logarithmic_error: 10.2744
Epoch 3/150
786/786 [==============================] - 10s 13ms/step - loss: 9.7360 - mean_squared_logarithmic_error: 9.7360 - val_loss: 9.3578 - val_mean_squared_logarithmic_error: 9.3578
Epoch 4/150
786/786 [==============================] - 10s 12ms/step - loss: 8.1382 - mean_squared_logarithmic_error: 8.1382 - val_loss: 7.9453 - val_mean_squared_logarithmic_error: 7.9453
Epoch 5/150
786/786 [==============================] - 10s 13ms/step - loss: 6.7231 - mean_squared_logarithmic_error: 6.7231 - val_loss: 6.7068 - val_mean_squared_logarithmic_error: 6.7068
Epoch 6/150
786/786 [===========================

In [15]:
model.save("chess2000r1000r200r1r.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess2000r1000r200r1r.tf\assets


INFO:tensorflow:Assets written to: chess2000r1000r200r1r.tf\assets


In [16]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation="relu")])
model.compile(loss="mean_squared_logarithmic_error", optimizer="sgd", metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
786/786 [==============================] - 12s 14ms/step - loss: 12.1534 - mean_squared_logarithmic_error: 12.1534 - val_loss: 11.4858 - val_mean_squared_logarithmic_error: 11.4858
Epoch 2/150
786/786 [==============================] - 11s 13ms/step - loss: 11.1342 - mean_squared_logarithmic_error: 11.1342 - val_loss: 10.4302 - val_mean_squared_logarithmic_error: 10.4302
Epoch 3/150
786/786 [==============================] - 13s 17ms/step - loss: 9.9660 - mean_squared_logarithmic_error: 9.9660 - val_loss: 9.2712 - val_mean_squared_logarithmic_error: 9.2712
Epoch 4/150
786/786 [==============================] - 14s 17ms/step - loss: 8.4823 - mean_squared_logarithmic_error: 8.4823 - val_loss: 7.8835 - val_mean_squared_logarithmic_error: 7.8835
Epoch 5/150
786/786 [==============================] - 12s 15ms/step - loss: 7.0318 - mean_squared_logarithmic_error: 7.0318 - val_loss: 7.9909 - val_mean_squared_logarithmic_error: 7.9909
Epoch 6/150
786/786 [==========================

In [17]:
model.save("chess2000r1000r200r1rDO.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess2000r1000r200r1rDO.tf\assets


INFO:tensorflow:Assets written to: chess2000r1000r200r1rDO.tf\assets
