In [1]:
import os
import numpy as np
import pandas as pd
import sklearn.model_selection
import tensorflow as tf

import EvaluationDataAccess as DataAccess

In [2]:
print(os.getcwd())

C:\Users\Piotr\Documents\proj\chess\ml-poc


In [3]:
X, Y = DataAccess.get_all_evaluated_records()
X = np.array([DataAccess.fen_positon_to_one_hot_vector(fen) for fen in X])

X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, Y, test_size=0.33)

In [4]:
print(X_train)

[[ 1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [-1  0  0 ...  0  0  0]
 ...
 [ 1  0  0 ...  0  0  0]
 [ 1  1  1 ...  0  0  0]
 [-1  0  0 ...  0  0  0]]


In [5]:
print(X.shape)

(55190, 837)


In [7]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(500, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1, activation="relu")])

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9, nesterov=True)
model.compile(loss="mean_squared_logarithmic_error", optimizer=optimizer, metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
1156/1156 [==============================] - 6s 5ms/step - loss: 9.8492 - mean_squared_logarithmic_error: 9.8492 - val_loss: 7.6782 - val_mean_squared_logarithmic_error: 7.6782
Epoch 2/150
1156/1156 [==============================] - 5s 4ms/step - loss: 6.4827 - mean_squared_logarithmic_error: 6.4827 - val_loss: 5.5892 - val_mean_squared_logarithmic_error: 5.5892
Epoch 3/150
1156/1156 [==============================] - 5s 4ms/step - loss: 4.8742 - mean_squared_logarithmic_error: 4.8742 - val_loss: 4.8437 - val_mean_squared_logarithmic_error: 4.8437
Epoch 4/150
1156/1156 [==============================] - 5s 4ms/step - loss: 3.8597 - mean_squared_logarithmic_error: 3.8597 - val_loss: 3.9872 - val_mean_squared_logarithmic_error: 3.9872
Epoch 5/150
1156/1156 [==============================] - 5s 4ms/step - loss: 3.3187 - mean_squared_logarithmic_error: 3.3187 - val_loss: 3.8155 - val_mean_squared_logarithmic_error: 3.8155
Epoch 6/150
1156/1156 [==============================] 

In [8]:
model.save("chess500r100r1r.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess500r100r1r.tf\assets


INFO:tensorflow:Assets written to: chess500r100r1r.tf\assets


In [10]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(500, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation="relu")])

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9, nesterov=True)
model.compile(loss="mean_squared_logarithmic_error", optimizer=optimizer, metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
1156/1156 [==============================] - 7s 6ms/step - loss: 9.9983 - mean_squared_logarithmic_error: 9.9983 - val_loss: 7.6481 - val_mean_squared_logarithmic_error: 7.6481
Epoch 2/150
1156/1156 [==============================] - 6s 5ms/step - loss: 6.7984 - mean_squared_logarithmic_error: 6.7984 - val_loss: 5.7274 - val_mean_squared_logarithmic_error: 5.7274
Epoch 3/150
1156/1156 [==============================] - 6s 5ms/step - loss: 5.3116 - mean_squared_logarithmic_error: 5.3116 - val_loss: 5.0036 - val_mean_squared_logarithmic_error: 5.0036
Epoch 4/150
1156/1156 [==============================] - 6s 5ms/step - loss: 4.4053 - mean_squared_logarithmic_error: 4.4053 - val_loss: 4.2759 - val_mean_squared_logarithmic_error: 4.2759
Epoch 5/150
1156/1156 [==============================] - 6s 5ms/step - loss: 3.8145 - mean_squared_logarithmic_error: 3.8145 - val_loss: 3.9894 - val_mean_squared_logarithmic_error: 3.9894
Epoch 6/150
1156/1156 [==============================] 

In [11]:
model.save("chess500r100r1rDO.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess500r100r1rDO.tf\assets


INFO:tensorflow:Assets written to: chess500r100r1rDO.tf\assets


In [12]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation="relu")])
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9, nesterov=True)
model.compile(loss="mean_squared_logarithmic_error", optimizer=optimizer, metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
1156/1156 [==============================] - 31s 26ms/step - loss: 8.8364 - mean_squared_logarithmic_error: 8.8364 - val_loss: 5.9445 - val_mean_squared_logarithmic_error: 5.9445
Epoch 2/150
1156/1156 [==============================] - 29s 25ms/step - loss: 5.2102 - mean_squared_logarithmic_error: 5.2102 - val_loss: 4.2175 - val_mean_squared_logarithmic_error: 4.2175
Epoch 3/150
1156/1156 [==============================] - 29s 25ms/step - loss: 3.6614 - mean_squared_logarithmic_error: 3.6614 - val_loss: 3.3844 - val_mean_squared_logarithmic_error: 3.3844
Epoch 4/150
1156/1156 [==============================] - 29s 25ms/step - loss: 2.8043 - mean_squared_logarithmic_error: 2.8043 - val_loss: 2.8920 - val_mean_squared_logarithmic_error: 2.8920
Epoch 5/150
1156/1156 [==============================] - 28s 25ms/step - loss: 2.3534 - mean_squared_logarithmic_error: 2.3534 - val_loss: 2.6180 - val_mean_squared_logarithmic_error: 2.6180
Epoch 6/150
1156/1156 [======================

In [13]:
model.save("chess2000r1000r200r1rDO.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess2000r1000r200r1rDO.tf\assets


INFO:tensorflow:Assets written to: chess2000r1000r200r1rDO.tf\assets


In [14]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation="relu")])
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9, nesterov=True)
model.compile(loss="mean_squared_logarithmic_error", optimizer=optimizer, metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
1156/1156 [==============================] - 38s 32ms/step - loss: 7.9479 - mean_squared_logarithmic_error: 7.9479 - val_loss: 5.4834 - val_mean_squared_logarithmic_error: 5.4834
Epoch 2/150
1156/1156 [==============================] - 34s 30ms/step - loss: 4.1425 - mean_squared_logarithmic_error: 4.1425 - val_loss: 3.3428 - val_mean_squared_logarithmic_error: 3.3428
Epoch 3/150
1156/1156 [==============================] - 36s 31ms/step - loss: 2.8766 - mean_squared_logarithmic_error: 2.8766 - val_loss: 3.1765 - val_mean_squared_logarithmic_error: 3.1765
Epoch 4/150
1156/1156 [==============================] - 36s 31ms/step - loss: 2.2867 - mean_squared_logarithmic_error: 2.2867 - val_loss: 2.3461 - val_mean_squared_logarithmic_error: 2.3461
Epoch 5/150
1156/1156 [==============================] - 35s 30ms/step - loss: 1.9712 - mean_squared_logarithmic_error: 1.9712 - val_loss: 2.2626 - val_mean_squared_logarithmic_error: 2.2626
Epoch 6/150
1156/1156 [======================

In [15]:
model.save("chess5x1000r1rDO.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess5x1000r1rDO.tf\assets


INFO:tensorflow:Assets written to: chess5x1000r1rDO.tf\assets


In [16]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2000, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation="relu")])
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9, nesterov=True)
model.compile(loss="mean_squared_logarithmic_error", optimizer=optimizer, metrics=["mean_squared_logarithmic_error"])

history = model.fit(X_train, y_train, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
1156/1156 [==============================] - 159s 136ms/step - loss: 7.7597 - mean_squared_logarithmic_error: 7.7597 - val_loss: 4.5282 - val_mean_squared_logarithmic_error: 4.5282
Epoch 2/150
1156/1156 [==============================] - 156s 135ms/step - loss: 3.8668 - mean_squared_logarithmic_error: 3.8668 - val_loss: 3.2836 - val_mean_squared_logarithmic_error: 3.2836
Epoch 3/150
1156/1156 [==============================] - 154s 133ms/step - loss: 2.7617 - mean_squared_logarithmic_error: 2.7617 - val_loss: 2.6329 - val_mean_squared_logarithmic_error: 2.6329
Epoch 4/150
1156/1156 [==============================] - 152s 131ms/step - loss: 2.2148 - mean_squared_logarithmic_error: 2.2148 - val_loss: 2.6721 - val_mean_squared_logarithmic_error: 2.6721
Epoch 5/150
1156/1156 [==============================] - 151s 131ms/step - loss: 1.9770 - mean_squared_logarithmic_error: 1.9770 - val_loss: 2.3903 - val_mean_squared_logarithmic_error: 2.3903
Epoch 6/150
1156/1156 [============

In [17]:
model.save("chess7x2000r1rDO.tf", save_format="tf")

INFO:tensorflow:Assets written to: chess7x2000r1rDO.tf\assets


INFO:tensorflow:Assets written to: chess7x2000r1rDO.tf\assets
